- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: 0075ca
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "feature"
  color: "ccf5ff"
  description: "This adds some form of new functionality"
- name: "breaking change"
  color: "efa7ae"
  description: "This breaks existing behavior"
- name: "mysterious"
  color: "cccccc"
  description: "We forgot to label this"
- name: "chore"
  color: "27127c"
  description: "Just keeping things neat and tidy"
- name: "dependencies"
  color: "edc397"
  description: "Pull requests that update a dependency file"
- name: "merge"
  color: "98ed98"
  description: "Shipit!"
- name: "deprecated"
  color: "dd824d"
  description: "Deprecated functionality"
- name: "removed"
  color: "fce99f"
  description: "Removed functionality"
- name: "security"
  color: "cbce1e"
  description: "Security related issue"
